CREATE TABLE states (
    state_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_name VARCHAR(100) NOT NULL UNIQUE,
    state_code VARCHAR(10) UNIQUE
);

CREATE TABLE districts (
    district_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_id BIGINT NOT NULL REFERENCES states(state_id),
    district_name VARCHAR(120) NOT NULL,
    UNIQUE (state_id, district_name)
);

CREATE TABLE villages (
    village_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id BIGINT NOT NULL REFERENCES districts(district_id),
    village_name VARCHAR(150) NOT NULL,
    village_code VARCHAR(30),
    UNIQUE (district_id, village_name)
);
