CREATE TABLE organizations (
    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name VARCHAR(200) NOT NULL,
    organization_type VARCHAR(60) NOT NULL,
    parent_organization_id BIGINT REFERENCES organizations(organization_id),
    state_id BIGINT REFERENCES states(state_id),
    district_id BIGINT REFERENCES districts(district_id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
