CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(60) NOT NULL UNIQUE
);

INSERT INTO roles (role_name) VALUES
('System Administrator'),
('Government Officer'),
('Project Agency'),
('Acquisition Officer'),
('Field Officer')
ON CONFLICT (role_name) DO NOTHING;

CREATE TABLE permissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    firebase_uid VARCHAR(128) UNIQUE,
    full_name VARCHAR(150) NOT NULL,
    official_email VARCHAR(254) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles(role_id),
    organization_id BIGINT REFERENCES organizations(organization_id),
    administrative_level VARCHAR(20) CHECK (administrative_level IN ('CENTRAL','STATE','DISTRICT')),
    state_id BIGINT REFERENCES states(state_id),
    district_id BIGINT REFERENCES districts(district_id),
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE','INACTIVE','SUSPENDED','PENDING')),
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (district_id IS NULL OR state_id IS NOT NULL)
);

CREATE TABLE user_scope_assignments (
    scope_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    state_id BIGINT REFERENCES states(state_id),
    district_id BIGINT REFERENCES districts(district_id),
    organization_id BIGINT REFERENCES organizations(organization_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (state_id IS NOT NULL OR district_id IS NOT NULL OR organization_id IS NOT NULL)
);
