CREATE TABLE projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(40) NOT NULL UNIQUE,
    project_name VARCHAR(250) NOT NULL,
    description TEXT,
    project_category VARCHAR(100),
    implementing_organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    created_by UUID NOT NULL REFERENCES users(user_id),
    state_id BIGINT NOT NULL REFERENCES states(state_id),
    district_id BIGINT REFERENCES districts(district_id),
    project_location TEXT,
    proposed_area_hectare NUMERIC(14,4) NOT NULL DEFAULT 0 CHECK (proposed_area_hectare >= 0),
    project_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    planned_start_date DATE,
    planned_end_date DATE,
    actual_start_date DATE,
    actual_end_date DATE,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (planned_end_date IS NULL OR planned_start_date IS NULL OR planned_end_date >= planned_start_date)
);

CREATE TABLE project_members (
    project_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    project_role VARCHAR(60) NOT NULL,
    assigned_by UUID REFERENCES users(user_id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, user_id, project_role)
);

CREATE TABLE proposals (
    proposal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    proposal_version INTEGER NOT NULL DEFAULT 1 CHECK (proposal_version > 0),
    proposal_title VARCHAR(250) NOT NULL,
    proposal_description TEXT,
    proposed_area_hectare NUMERIC(14,4) CHECK (proposed_area_hectare >= 0),
    submitted_by UUID REFERENCES users(user_id),
    proposal_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    submitted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, proposal_version)
);
