CREATE TABLE workflow_definitions (
    workflow_definition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_name VARCHAR(150) NOT NULL,
    workflow_version INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (workflow_name, workflow_version)
);

CREATE TABLE workflow_stages (
    workflow_stage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_definition_id BIGINT NOT NULL REFERENCES workflow_definitions(workflow_definition_id) ON DELETE CASCADE,
    stage_code VARCHAR(50) NOT NULL,
    stage_name VARCHAR(150) NOT NULL,
    stage_order INTEGER NOT NULL CHECK (stage_order > 0),
    responsible_role_id BIGINT REFERENCES roles(role_id),
    target_days INTEGER CHECK (target_days IS NULL OR target_days >= 0),
    is_approval_stage BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (workflow_definition_id, stage_code),
    UNIQUE (workflow_definition_id, stage_order)
);

CREATE TABLE project_workflows (
    project_workflow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    workflow_definition_id BIGINT NOT NULL REFERENCES workflow_definitions(workflow_definition_id),
    current_stage_id BIGINT REFERENCES workflow_stages(workflow_stage_id),
    workflow_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    UNIQUE (project_id, workflow_definition_id)
);

CREATE TABLE workflow_actions (
    workflow_action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_workflow_id BIGINT NOT NULL REFERENCES project_workflows(project_workflow_id) ON DELETE CASCADE,
    workflow_stage_id BIGINT REFERENCES workflow_stages(workflow_stage_id),
    performed_by UUID REFERENCES users(user_id),
    action_type VARCHAR(50) NOT NULL,
    action_status VARCHAR(30),
    remarks TEXT,
    acted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE proposal_reviews (
    proposal_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL REFERENCES proposals(proposal_id) ON DELETE CASCADE,
    reviewer_id UUID NOT NULL REFERENCES users(user_id),
    review_level VARCHAR(20) CHECK (review_level IN ('CENTRAL','STATE','DISTRICT')),
    decision VARCHAR(30) NOT NULL CHECK (decision IN ('SUBMITTED','UNDER_REVIEW','RETURNED','APPROVED','REJECTED')),
    remarks TEXT,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project_milestones (
    milestone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    milestone_name VARCHAR(180) NOT NULL,
    description TEXT,
    planned_date DATE,
    actual_date DATE,
    milestone_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    responsible_user_id UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (actual_date IS NULL OR planned_date IS NULL OR actual_date >= planned_date OR milestone_status = 'COMPLETED')
);
