CREATE TABLE land_parcels (
    parcel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    village_id BIGINT NOT NULL REFERENCES villages(village_id),
    survey_number VARCHAR(80) NOT NULL,
    subdivision_number VARCHAR(80),
    area_hectare NUMERIC(14,4) NOT NULL CHECK (area_hectare >= 0),
    land_type VARCHAR(80),
    ownership_type VARCHAR(80),
    acquisition_status VARCHAR(40) NOT NULL DEFAULT 'PROPOSED',
    geom geometry(MULTIPOLYGON, 4326),
    centroid geometry(POINT, 4326),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, village_id, survey_number, subdivision_number)
);

CREATE TABLE parcel_owners (
    owner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name VARCHAR(180) NOT NULL,
    phone VARCHAR(30),
    email VARCHAR(254),
    address TEXT,
    identity_reference_encrypted TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parcel_ownerships (
    parcel_ownership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    owner_id BIGINT NOT NULL REFERENCES parcel_owners(owner_id),
    ownership_percent NUMERIC(5,2) CHECK (ownership_percent > 0 AND ownership_percent <= 100),
    ownership_start_date DATE,
    ownership_end_date DATE,
    record_source VARCHAR(150),
    verified_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    UNIQUE (parcel_id, owner_id, ownership_start_date)
);

CREATE TABLE gis_layers (
    gis_layer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    layer_name VARCHAR(150) NOT NULL,
    layer_type VARCHAR(80),
    geom geometry(Geometry, 4326) NOT NULL,
    properties JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
