CREATE TABLE parcel_field_verifications (
    verification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    field_officer_id UUID NOT NULL REFERENCES users(user_id),
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    verified_location geometry(POINT, 4326),
    observations TEXT,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE field_tasks (
    field_task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    assigned_to UUID NOT NULL REFERENCES users(user_id),
    assigned_by UUID REFERENCES users(user_id),
    task_title VARCHAR(180) NOT NULL,
    task_description TEXT,
    task_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    due_date DATE,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE field_observations (
    field_observation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_task_id BIGINT REFERENCES field_tasks(field_task_id) ON DELETE SET NULL,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    submitted_by UUID NOT NULL REFERENCES users(user_id),
    observation_text TEXT NOT NULL,
    location geometry(POINT, 4326),
    observed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parcel_photos (
    parcel_photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    uploaded_by UUID NOT NULL REFERENCES users(user_id),
    file_path TEXT NOT NULL,
    caption TEXT,
    location geometry(POINT, 4326),
    captured_at TIMESTAMPTZ,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
