CREATE TABLE acquisition_notifications (
    acquisition_notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    notification_number VARCHAR(100),
    notification_type VARCHAR(80) NOT NULL,
    title VARCHAR(250) NOT NULL,
    issue_date DATE,
    publication_date DATE,
    effective_date DATE,
    description TEXT,
    document_id BIGINT,
    created_by UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification_parcels (
    acquisition_notification_id BIGINT NOT NULL REFERENCES acquisition_notifications(acquisition_notification_id) ON DELETE CASCADE,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    PRIMARY KEY (acquisition_notification_id, parcel_id)
);

CREATE TABLE claims (
    claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    claimant_owner_id BIGINT REFERENCES parcel_owners(owner_id),
    claim_type VARCHAR(80),
    claim_text TEXT NOT NULL,
    claim_status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by UUID REFERENCES users(user_id),
    resolved_at TIMESTAMPTZ,
    resolution_remarks TEXT
);

CREATE TABLE awards (
    award_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    award_number VARCHAR(100) NOT NULL,
    award_date DATE,
    award_amount NUMERIC(16,2) CHECK (award_amount >= 0),
    award_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    declared_by UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, award_number)
);
