CREATE TABLE compensation_assessments (
    compensation_assessment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_id BIGINT NOT NULL REFERENCES awards(award_id) ON DELETE CASCADE,
    owner_id BIGINT NOT NULL REFERENCES parcel_owners(owner_id),
    assessed_amount NUMERIC(16,2) NOT NULL CHECK (assessed_amount >= 0),
    approved_amount NUMERIC(16,2) CHECK (approved_amount >= 0),
    assessment_basis TEXT,
    assessment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    assessed_by UUID REFERENCES users(user_id),
    approved_by UUID REFERENCES users(user_id),
    assessed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMPTZ,
    UNIQUE (award_id, owner_id)
);

CREATE TABLE compensation_payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compensation_assessment_id BIGINT NOT NULL REFERENCES compensation_assessments(compensation_assessment_id) ON DELETE CASCADE,
    amount_paid NUMERIC(16,2) NOT NULL CHECK (amount_paid > 0),
    payment_date DATE,
    transaction_reference VARCHAR(150),
    payment_method VARCHAR(50),
    payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    recorded_by UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
