CREATE TABLE affected_families (
    family_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT REFERENCES land_parcels(parcel_id) ON DELETE SET NULL,
    family_reference_code VARCHAR(80),
    head_of_family_name VARCHAR(180),
    household_size INTEGER CHECK (household_size IS NULL OR household_size >= 0),
    displacement_status VARCHAR(30) NOT NULL DEFAULT 'NOT_ASSESSED',
    vulnerability_category VARCHAR(100),
    assessment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, family_reference_code)
);

CREATE TABLE family_members (
    family_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id BIGINT NOT NULL REFERENCES affected_families(family_id) ON DELETE CASCADE,
    full_name VARCHAR(180),
    relationship_to_head VARCHAR(80),
    age_years INTEGER CHECK (age_years IS NULL OR age_years >= 0),
    livelihood VARCHAR(150),
    is_displaced BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE rr_assessments (
    rr_assessment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id BIGINT NOT NULL REFERENCES affected_families(family_id) ON DELETE CASCADE,
    assessment_date DATE,
    assessed_by UUID REFERENCES users(user_id),
    assessment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rr_benefits (
    rr_benefit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id BIGINT NOT NULL REFERENCES affected_families(family_id) ON DELETE CASCADE,
    benefit_type VARCHAR(100) NOT NULL,
    benefit_description TEXT,
    assessed_value NUMERIC(16,2) CHECK (assessed_value IS NULL OR assessed_value >= 0),
    approved_value NUMERIC(16,2) CHECK (approved_value IS NULL OR approved_value >= 0),
    benefit_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    approved_by UUID REFERENCES users(user_id),
    approved_at TIMESTAMPTZ
);

CREATE TABLE rr_deliveries (
    rr_delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rr_benefit_id BIGINT NOT NULL REFERENCES rr_benefits(rr_benefit_id) ON DELETE CASCADE,
    delivery_date DATE,
    delivery_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    delivery_reference VARCHAR(150),
    remarks TEXT,
    recorded_by UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
