CREATE TABLE possession_records (
    possession_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    possession_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    possession_date DATE,
    handed_over_by UUID REFERENCES users(user_id),
    received_by UUID REFERENCES users(user_id),
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
