CREATE TABLE documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    document_type VARCHAR(100),
    document_title VARCHAR(250) NOT NULL,
    uploaded_by UUID NOT NULL REFERENCES users(user_id),
    current_version INTEGER NOT NULL DEFAULT 1 CHECK (current_version > 0),
    is_confidential BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (project_id IS NOT NULL OR parcel_id IS NOT NULL)
);

CREATE TABLE document_versions (
    document_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL CHECK (version_number > 0),
    file_path TEXT NOT NULL,
    file_hash VARCHAR(128),
    file_size_bytes BIGINT CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    uploaded_by UUID NOT NULL REFERENCES users(user_id),
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version_notes TEXT,
    UNIQUE (document_id, version_number)
);

ALTER TABLE acquisition_notifications
ADD CONSTRAINT fk_acquisition_notification_document
FOREIGN KEY (document_id) REFERENCES documents(document_id) ON DELETE SET NULL;

CREATE TABLE document_reviews (
    document_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    reviewer_id UUID NOT NULL REFERENCES users(user_id),
    review_status VARCHAR(30) NOT NULL,
    remarks TEXT,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE acquisition_notifications
ADD CONSTRAINT fk_acquisition_notification_document
FOREIGN KEY (document_id) REFERENCES documents(document_id) ON DELETE SET NULL;
