CREATE TABLE external_system_integrations (
    integration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_name VARCHAR(180) NOT NULL,
    integration_type VARCHAR(80) NOT NULL,
    endpoint_reference TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
