CREATE TABLE analytics_snapshots (
    analytics_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
    state_id BIGINT REFERENCES states(state_id),
    snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
    area_proposed_hectare NUMERIC(16,4) NOT NULL DEFAULT 0,
    area_notified_hectare NUMERIC(16,4) NOT NULL DEFAULT 0,
    area_acquired_hectare NUMERIC(16,4) NOT NULL DEFAULT 0,
    compensation_assessed NUMERIC(16,2) NOT NULL DEFAULT 0,
    compensation_paid NUMERIC(16,2) NOT NULL DEFAULT 0,
    affected_family_count INTEGER NOT NULL DEFAULT 0,
    displaced_family_count INTEGER NOT NULL DEFAULT 0,
    rr_completed_family_count INTEGER NOT NULL DEFAULT 0,
    parcels_in_possession INTEGER NOT NULL DEFAULT 0,
    parcels_total INTEGER NOT NULL DEFAULT 0,
    UNIQUE (project_id, state_id, snapshot_date)
);
