CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE states (
    state_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_name VARCHAR(100) NOT NULL UNIQUE,
    state_code VARCHAR(10) UNIQUE
);

CREATE TABLE districts (
    district_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_id BIGINT NOT NULL REFERENCES states(state_id),
    district_name VARCHAR(120) NOT NULL,
    UNIQUE (state_id, district_name)
);

CREATE TABLE villages (
    village_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id BIGINT NOT NULL REFERENCES districts(district_id),
    village_name VARCHAR(150) NOT NULL,
    village_code VARCHAR(30),
    UNIQUE (district_id, village_name)
);

CREATE TABLE organizations (
    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name VARCHAR(200) NOT NULL,
    organization_type VARCHAR(60) NOT NULL,
    parent_organization_id BIGINT REFERENCES organizations(organization_id),
    state_id BIGINT REFERENCES states(state_id),
    district_id BIGINT REFERENCES districts(district_id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(60) NOT NULL UNIQUE
);

INSERT INTO roles (role_name) VALUES
('System Administrator'),
('Government Officer'),
('Project Agency'),
('Acquisition Officer'),
('Field Officer')
ON CONFLICT (role_name) DO NOTHING;

CREATE TABLE permissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name VARCHAR(150) NOT NULL,
    official_email VARCHAR(254) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles(role_id),
    organization_id BIGINT REFERENCES organizations(organization_id),
    administrative_level VARCHAR(20) CHECK (administrative_level IN ('CENTRAL','STATE','DISTRICT')),
    state_id BIGINT REFERENCES states(state_id),
    district_id BIGINT REFERENCES districts(district_id),
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE','INACTIVE','SUSPENDED','PENDING')),
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (district_id IS NULL OR state_id IS NOT NULL)
);

CREATE TABLE user_scope_assignments (
    scope_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    state_id BIGINT REFERENCES states(state_id),
    district_id BIGINT REFERENCES districts(district_id),
    organization_id BIGINT REFERENCES organizations(organization_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (state_id IS NOT NULL OR district_id IS NOT NULL OR organization_id IS NOT NULL)
);

CREATE TABLE projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(40) NOT NULL UNIQUE,
    project_name VARCHAR(250) NOT NULL,
    description TEXT,
    project_category VARCHAR(100),
    implementing_organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    created_by UUID NOT NULL REFERENCES users(user_id),
    state_id BIGINT NOT NULL REFERENCES states(state_id),
    district_id BIGINT REFERENCES districts(district_id),
    project_location TEXT,
    proposed_area_hectare NUMERIC(14,4) NOT NULL DEFAULT 0 CHECK (proposed_area_hectare >= 0),
    project_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    planned_start_date DATE,
    planned_end_date DATE,
    actual_start_date DATE,
    actual_end_date DATE,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (planned_end_date IS NULL OR planned_start_date IS NULL OR planned_end_date >= planned_start_date)
);

CREATE TABLE project_members (
    project_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    project_role VARCHAR(60) NOT NULL,
    assigned_by UUID REFERENCES users(user_id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, user_id, project_role)
);

CREATE TABLE proposals (
    proposal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    proposal_version INTEGER NOT NULL DEFAULT 1 CHECK (proposal_version > 0),
    proposal_title VARCHAR(250) NOT NULL,
    proposal_description TEXT,
    proposed_area_hectare NUMERIC(14,4) CHECK (proposed_area_hectare >= 0),
    submitted_by UUID REFERENCES users(user_id),
    proposal_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    submitted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, proposal_version)
);

CREATE TABLE workflow_definitions (
    workflow_definition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_name VARCHAR(150) NOT NULL,
    workflow_version INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (workflow_name, workflow_version)
);

CREATE TABLE workflow_stages (
    workflow_stage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_definition_id BIGINT NOT NULL REFERENCES workflow_definitions(workflow_definition_id) ON DELETE CASCADE,
    stage_code VARCHAR(50) NOT NULL,
    stage_name VARCHAR(150) NOT NULL,
    stage_order INTEGER NOT NULL CHECK (stage_order > 0),
    responsible_role_id BIGINT REFERENCES roles(role_id),
    target_days INTEGER CHECK (target_days IS NULL OR target_days >= 0),
    is_approval_stage BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (workflow_definition_id, stage_code),
    UNIQUE (workflow_definition_id, stage_order)
);

CREATE TABLE project_workflows (
    project_workflow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    workflow_definition_id BIGINT NOT NULL REFERENCES workflow_definitions(workflow_definition_id),
    current_stage_id BIGINT REFERENCES workflow_stages(workflow_stage_id),
    workflow_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    UNIQUE (project_id, workflow_definition_id)
);

CREATE TABLE workflow_actions (
    workflow_action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_workflow_id BIGINT NOT NULL REFERENCES project_workflows(project_workflow_id) ON DELETE CASCADE,
    workflow_stage_id BIGINT REFERENCES workflow_stages(workflow_stage_id),
    performed_by UUID REFERENCES users(user_id),
    action_type VARCHAR(50) NOT NULL,
    action_status VARCHAR(30),
    remarks TEXT,
    acted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE proposal_reviews (
    proposal_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL REFERENCES proposals(proposal_id) ON DELETE CASCADE,
    reviewer_id UUID NOT NULL REFERENCES users(user_id),
    review_level VARCHAR(20) CHECK (review_level IN ('CENTRAL','STATE','DISTRICT')),
    decision VARCHAR(30) NOT NULL CHECK (decision IN ('SUBMITTED','UNDER_REVIEW','RETURNED','APPROVED','REJECTED')),
    remarks TEXT,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project_milestones (
    milestone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    milestone_name VARCHAR(180) NOT NULL,
    description TEXT,
    planned_date DATE,
    actual_date DATE,
    milestone_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    responsible_user_id UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (actual_date IS NULL OR planned_date IS NULL OR actual_date >= planned_date OR milestone_status = 'COMPLETED')
);

CREATE TABLE land_parcels (
    parcel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    village_id BIGINT NOT NULL REFERENCES villages(village_id),
    survey_number VARCHAR(80) NOT NULL,
    subdivision_number VARCHAR(80),
    area_hectare NUMERIC(14,4) NOT NULL CHECK (area_hectare >= 0),
    land_type VARCHAR(80),
    ownership_type VARCHAR(80),
    acquisition_status VARCHAR(40) NOT NULL DEFAULT 'PROPOSED',
    geom geometry(MULTIPOLYGON, 4326),
    centroid geometry(POINT, 4326),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, village_id, survey_number, subdivision_number)
);

CREATE TABLE parcel_owners (
    owner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name VARCHAR(180) NOT NULL,
    phone VARCHAR(30),
    email VARCHAR(254),
    address TEXT,
    identity_reference_encrypted TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parcel_ownerships (
    parcel_ownership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    owner_id BIGINT NOT NULL REFERENCES parcel_owners(owner_id),
    ownership_percent NUMERIC(5,2) CHECK (ownership_percent > 0 AND ownership_percent <= 100),
    ownership_start_date DATE,
    ownership_end_date DATE,
    record_source VARCHAR(150),
    verified_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    UNIQUE (parcel_id, owner_id, ownership_start_date)
);

CREATE TABLE gis_layers (
    gis_layer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    layer_name VARCHAR(150) NOT NULL,
    layer_type VARCHAR(80),
    geom geometry(Geometry, 4326) NOT NULL,
    properties JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parcel_field_verifications (
    verification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    field_officer_id UUID NOT NULL REFERENCES users(user_id),
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    verified_location geometry(POINT, 4326),
    observations TEXT,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE field_tasks (
    field_task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    assigned_to UUID NOT NULL REFERENCES users(user_id),
    assigned_by UUID REFERENCES users(user_id),
    task_title VARCHAR(180) NOT NULL,
    task_description TEXT,
    task_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    due_date DATE,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE field_observations (
    field_observation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_task_id BIGINT REFERENCES field_tasks(field_task_id) ON DELETE SET NULL,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    submitted_by UUID NOT NULL REFERENCES users(user_id),
    observation_text TEXT NOT NULL,
    location geometry(POINT, 4326),
    observed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parcel_photos (
    parcel_photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    uploaded_by UUID NOT NULL REFERENCES users(user_id),
    file_path TEXT NOT NULL,
    caption TEXT,
    location geometry(POINT, 4326),
    captured_at TIMESTAMPTZ,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE acquisition_notifications (
    acquisition_notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    notification_number VARCHAR(100),
    notification_type VARCHAR(80) NOT NULL,
    title VARCHAR(250) NOT NULL,
    issue_date DATE,
    publication_date DATE,
    effective_date DATE,
    description TEXT,
    document_id BIGINT,
    created_by UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification_parcels (
    acquisition_notification_id BIGINT NOT NULL REFERENCES acquisition_notifications(acquisition_notification_id) ON DELETE CASCADE,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    PRIMARY KEY (acquisition_notification_id, parcel_id)
);

CREATE TABLE claims (
    claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    claimant_owner_id BIGINT REFERENCES parcel_owners(owner_id),
    claim_type VARCHAR(80),
    claim_text TEXT NOT NULL,
    claim_status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by UUID REFERENCES users(user_id),
    resolved_at TIMESTAMPTZ,
    resolution_remarks TEXT
);

CREATE TABLE awards (
    award_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    award_number VARCHAR(100) NOT NULL,
    award_date DATE,
    award_amount NUMERIC(16,2) CHECK (award_amount >= 0),
    award_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    declared_by UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, award_number)
);

CREATE TABLE compensation_assessments (
    compensation_assessment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_id BIGINT NOT NULL REFERENCES awards(award_id) ON DELETE CASCADE,
    owner_id BIGINT NOT NULL REFERENCES parcel_owners(owner_id),
    assessed_amount NUMERIC(16,2) NOT NULL CHECK (assessed_amount >= 0),
    approved_amount NUMERIC(16,2) CHECK (approved_amount >= 0),
    assessment_basis TEXT,
    assessment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    assessed_by UUID REFERENCES users(user_id),
    approved_by UUID REFERENCES users(user_id),
    assessed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMPTZ,
    UNIQUE (award_id, owner_id)
);

CREATE TABLE compensation_payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compensation_assessment_id BIGINT NOT NULL REFERENCES compensation_assessments(compensation_assessment_id) ON DELETE CASCADE,
    amount_paid NUMERIC(16,2) NOT NULL CHECK (amount_paid > 0),
    payment_date DATE,
    transaction_reference VARCHAR(150),
    payment_method VARCHAR(50),
    payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    recorded_by UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE affected_families (
    family_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT REFERENCES land_parcels(parcel_id) ON DELETE SET NULL,
    family_reference_code VARCHAR(80),
    head_of_family_name VARCHAR(180),
    household_size INTEGER CHECK (household_size IS NULL OR household_size >= 0),
    displacement_status VARCHAR(30) NOT NULL DEFAULT 'NOT_ASSESSED',
    vulnerability_category VARCHAR(100),
    assessment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, family_reference_code)
);

CREATE TABLE family_members (
    family_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id BIGINT NOT NULL REFERENCES affected_families(family_id) ON DELETE CASCADE,
    full_name VARCHAR(180),
    relationship_to_head VARCHAR(80),
    age_years INTEGER CHECK (age_years IS NULL OR age_years >= 0),
    livelihood VARCHAR(150),
    is_displaced BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE rr_assessments (
    rr_assessment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id BIGINT NOT NULL REFERENCES affected_families(family_id) ON DELETE CASCADE,
    assessment_date DATE,
    assessed_by UUID REFERENCES users(user_id),
    assessment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rr_benefits (
    rr_benefit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id BIGINT NOT NULL REFERENCES affected_families(family_id) ON DELETE CASCADE,
    benefit_type VARCHAR(100) NOT NULL,
    benefit_description TEXT,
    assessed_value NUMERIC(16,2) CHECK (assessed_value IS NULL OR assessed_value >= 0),
    approved_value NUMERIC(16,2) CHECK (approved_value IS NULL OR approved_value >= 0),
    benefit_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    approved_by UUID REFERENCES users(user_id),
    approved_at TIMESTAMPTZ
);

CREATE TABLE rr_deliveries (
    rr_delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rr_benefit_id BIGINT NOT NULL REFERENCES rr_benefits(rr_benefit_id) ON DELETE CASCADE,
    delivery_date DATE,
    delivery_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    delivery_reference VARCHAR(150),
    remarks TEXT,
    recorded_by UUID REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE possession_records (
    possession_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    possession_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    possession_date DATE,
    handed_over_by UUID REFERENCES users(user_id),
    received_by UUID REFERENCES users(user_id),
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
    parcel_id BIGINT REFERENCES land_parcels(parcel_id) ON DELETE CASCADE,
    document_type VARCHAR(100),
    document_title VARCHAR(250) NOT NULL,
    uploaded_by UUID NOT NULL REFERENCES users(user_id),
    current_version INTEGER NOT NULL DEFAULT 1 CHECK (current_version > 0),
    is_confidential BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (project_id IS NOT NULL OR parcel_id IS NOT NULL)
);

CREATE TABLE document_versions (
    document_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL CHECK (version_number > 0),
    file_path TEXT NOT NULL,
    file_hash VARCHAR(128),
    file_size_bytes BIGINT CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    uploaded_by UUID NOT NULL REFERENCES users(user_id),
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version_notes TEXT,
    UNIQUE (document_id, version_number)
);

ALTER TABLE acquisition_notifications
ADD CONSTRAINT fk_acquisition_notification_document
FOREIGN KEY (document_id) REFERENCES documents(document_id) ON DELETE SET NULL;

CREATE TABLE document_reviews (
    document_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    reviewer_id UUID NOT NULL REFERENCES users(user_id),
    review_status VARCHAR(30) NOT NULL,
    remarks TEXT,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE in_app_notifications (
    in_app_notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
    title VARCHAR(250) NOT NULL,
    message TEXT NOT NULL,
    notification_type VARCHAR(80),
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(user_id) ON DELETE SET NULL,
    action VARCHAR(120) NOT NULL,
    entity_table VARCHAR(120) NOT NULL,
    entity_id VARCHAR(120),
    old_values JSONB,
    new_values JSONB,
    ip_address INET,
    user_agent TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE external_system_integrations (
    integration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_name VARCHAR(180) NOT NULL,
    integration_type VARCHAR(80) NOT NULL,
    endpoint_reference TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE integration_sync_logs (
    sync_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id BIGINT NOT NULL REFERENCES external_system_integrations(integration_id) ON DELETE CASCADE,
    sync_started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sync_completed_at TIMESTAMPTZ,
    sync_status VARCHAR(30) NOT NULL,
    records_processed INTEGER NOT NULL DEFAULT 0 CHECK (records_processed >= 0),
    error_details TEXT
);

CREATE TABLE analytics_snapshots (
    analytics_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(project_id) ON DELETE CASCADE,
    state_id BIGINT REFERENCES states(state_id),
    snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
    area_proposed_hectare NUMERIC(16,4) NOT NULL DEFAULT 0,
    area_notified_hectare NUMERIC(16,4) NOT NULL DEFAULT 0,
    area_acquired_hectare NUMERIC(16,4) NOT NULL DEFAULT 0,
    compensation_assessed NUMERIC(16,2) NOT NULL DEFAULT 0,
    compensation_paid NUMERIC(16,2) NOT NULL DEFAULT 0,
    affected_family_count INTEGER NOT NULL DEFAULT 0,
    displaced_family_count INTEGER NOT NULL DEFAULT 0,
    rr_completed_family_count INTEGER NOT NULL DEFAULT 0,
    parcels_in_possession INTEGER NOT NULL DEFAULT 0,
    parcels_total INTEGER NOT NULL DEFAULT 0,
    UNIQUE (project_id, state_id, snapshot_date)
);

CREATE INDEX idx_projects_state_status ON projects(state_id, project_status);
CREATE INDEX idx_projects_district ON projects(district_id);
CREATE INDEX idx_parcels_project_status ON land_parcels(project_id, acquisition_status);
CREATE INDEX idx_parcels_village_survey ON land_parcels(village_id, survey_number);
CREATE INDEX idx_parcels_geom ON land_parcels USING GIST(geom);
CREATE INDEX idx_parcels_centroid ON land_parcels USING GIST(centroid);
CREATE INDEX idx_gis_layers_geom ON gis_layers USING GIST(geom);
CREATE INDEX idx_field_verifications_location ON parcel_field_verifications USING GIST(verified_location);
CREATE INDEX idx_field_observations_location ON field_observations USING GIST(location);
CREATE INDEX idx_notifications_project_date ON acquisition_notifications(project_id, issue_date);
CREATE INDEX idx_compensation_status ON compensation_assessments(assessment_status);
CREATE INDEX idx_payments_status_date ON compensation_payments(payment_status, payment_date);
CREATE INDEX idx_rr_family_status ON rr_benefits(family_id, benefit_status);
CREATE INDEX idx_documents_project ON documents(project_id);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_table, entity_id);
CREATE INDEX idx_audit_logs_occurred_at ON audit_logs(occurred_at);
CREATE INDEX idx_in_app_notifications_recipient ON in_app_notifications(recipient_user_id, read_at);
