from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

print("\n" + "=" * 60)
print("LAND ACQUISITION ANALYTICS & CHARTS")
print("=" * 60)

CURRENT_DIR = Path(__file__).resolve().parent
AI_DIR = CURRENT_DIR.parent

# Prefer the output generated by main.py because it contains
# calculated risk scores and risk levels.
calculated_file = CURRENT_DIR / "risk_analysis_results.csv"
original_file = AI_DIR / "SIH26016_Land_Acquisition_Synthetic_Data.csv"

if calculated_file.exists():
    csv_file = calculated_file
    print("\nUsing calculated AI results:", csv_file)
elif original_file.exists():
    csv_file = original_file
    print("\nWARNING: Calculated results were not found.")
    print("Using original dataset:", original_file)
else:
    raise FileNotFoundError(
        "Neither risk_analysis_results.csv nor the original dataset was found."
    )

df = pd.read_csv(csv_file)

required_columns = [
    "payment_delay_days",
    "approval_delay_days",
    "acquisition_percent",
    "total_delay_days",
]

missing_columns = [column for column in required_columns if column not in df.columns]

if missing_columns:
    raise ValueError(f"Missing required columns: {missing_columns}")

for column in required_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce").fillna(0)

for column in ["state", "project_type", "ownership_dispute", "risk_level"]:
    if column in df.columns:
        df[column] = (
            df[column]
            .fillna("Unknown")
            .astype(str)
            .str.strip()
        )

if "risk_level" in df.columns:
    df["risk_level"] = df["risk_level"].str.upper()

output_dir = CURRENT_DIR / "analytics_outputs"
output_dir.mkdir(exist_ok=True)

# ------------------------------------------------------------
# 1. SUMMARY METRICS
# ------------------------------------------------------------

delayed_projects = df[df["total_delay_days"] > 30]
low_acquisition_projects = df[df["acquisition_percent"] < 70]
disputed_projects = df[
    df["ownership_dispute"].str.lower() == "yes"
]

summary = pd.DataFrame({
    "metric": [
        "Total records",
        "Delayed records (>30 days)",
        "Low acquisition records (<70%)",
        "Ownership dispute records",
        "Average total delay (days)",
        "Average payment delay (days)",
        "Average approval delay (days)",
        "Average acquisition progress (%)",
    ],
    "value": [
        len(df),
        len(delayed_projects),
        len(low_acquisition_projects),
        len(disputed_projects),
        round(df["total_delay_days"].mean(), 2),
        round(df["payment_delay_days"].mean(), 2),
        round(df["approval_delay_days"].mean(), 2),
        round(df["acquisition_percent"].mean(), 2),
    ],
})

summary.to_csv(output_dir / "analytics_summary.csv", index=False)

# ------------------------------------------------------------
# 2. RISK LEVEL DISTRIBUTION
# ------------------------------------------------------------

if "risk_level" in df.columns:
    risk_counts = df["risk_level"].value_counts().reindex(
        ["HIGH", "MEDIUM", "LOW"],
        fill_value=0,
    )

    plt.figure(figsize=(8, 5))
    ax = risk_counts.plot(kind="bar")
    plt.title("Risk Level Distribution")
    plt.xlabel("Risk Level")
    plt.ylabel("Number of Records")
    plt.xticks(rotation=0)

    for container in ax.containers:
        ax.bar_label(container)

    plt.tight_layout()
    plt.savefig(output_dir / "risk_level_distribution.png", dpi=200)
    plt.close()

    risk_counts.to_csv(output_dir / "risk_level_counts.csv")

# ------------------------------------------------------------
# 3. DELAY SEVERITY DISTRIBUTION
# ------------------------------------------------------------

def delay_category(days):
    if days <= 30:
        return "Low (0-30)"
    elif days <= 60:
        return "Moderate (31-60)"
    elif days <= 120:
        return "High (61-120)"
    return "Critical (>120)"

df["delay_category"] = df["total_delay_days"].apply(delay_category)

delay_order = [
    "Low (0-30)",
    "Moderate (31-60)",
    "High (61-120)",
    "Critical (>120)",
]

delay_counts = df["delay_category"].value_counts().reindex(
    delay_order,
    fill_value=0,
)

plt.figure(figsize=(9, 5))
ax = delay_counts.plot(kind="bar")
plt.title("Delay Severity Distribution")
plt.xlabel("Delay Category")
plt.ylabel("Number of Records")
plt.xticks(rotation=20)

for container in ax.containers:
    ax.bar_label(container)

plt.tight_layout()
plt.savefig(output_dir / "delay_severity_distribution.png", dpi=200)
plt.close()

delay_counts.to_csv(output_dir / "delay_severity_counts.csv")

# ------------------------------------------------------------
# 4. DELAY HISTOGRAM
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))
df["total_delay_days"].plot(kind="hist", bins=20)
plt.title("Distribution of Total Delay")
plt.xlabel("Total Delay (Days)")
plt.ylabel("Number of Records")
plt.tight_layout()
plt.savefig(output_dir / "total_delay_distribution.png", dpi=200)
plt.close()

# ------------------------------------------------------------
# 5. ACQUISITION PROGRESS GROUP ANALYSIS
# ------------------------------------------------------------

def acquisition_category(percent):
    if percent < 40:
        return "Very Low (<40%)"
    elif percent < 70:
        return "Moderate (40-69%)"
    return "Advanced (70-100%)"

df["acquisition_category"] = df["acquisition_percent"].apply(
    acquisition_category
)

acquisition_order = [
    "Very Low (<40%)",
    "Moderate (40-69%)",
    "Advanced (70-100%)",
]

acquisition_analysis = (
    df.groupby("acquisition_category", observed=False)
    .agg(
        record_count=("total_delay_days", "size"),
        average_delay_days=("total_delay_days", "mean"),
        average_acquisition_percent=("acquisition_percent", "mean"),
    )
    .reindex(acquisition_order)
)

acquisition_analysis["average_delay_days"] = (
    acquisition_analysis["average_delay_days"].round(2)
)
acquisition_analysis["average_acquisition_percent"] = (
    acquisition_analysis["average_acquisition_percent"].round(2)
)

acquisition_analysis.to_csv(
    output_dir / "acquisition_group_analysis.csv"
)

plt.figure(figsize=(9, 5))
acquisition_analysis["average_delay_days"].plot(kind="bar")
plt.title("Average Delay by Acquisition Progress Group")
plt.xlabel("Acquisition Progress Group")
plt.ylabel("Average Delay (Days)")
plt.xticks(rotation=20)
plt.tight_layout()
plt.savefig(
    output_dir / "average_delay_by_acquisition_group.png",
    dpi=200,
)
plt.close()

# ------------------------------------------------------------
# 6. DELAY VS ACQUISITION CORRELATION
# ------------------------------------------------------------

correlation = df[
    ["acquisition_percent", "total_delay_days"]
].corr().loc["acquisition_percent", "total_delay_days"]

correlation_result = pd.DataFrame({
    "metric": ["Correlation: acquisition vs total delay"],
    "value": [round(correlation, 4)],
})

correlation_result.to_csv(
    output_dir / "delay_acquisition_correlation.csv",
    index=False,
)

plt.figure(figsize=(8, 5))
plt.scatter(
    df["acquisition_percent"],
    df["total_delay_days"],
    alpha=0.6,
)
plt.title("Total Delay vs Acquisition Progress")
plt.xlabel("Acquisition Progress (%)")
plt.ylabel("Total Delay (Days)")
plt.tight_layout()
plt.savefig(output_dir / "delay_vs_acquisition.png", dpi=200)
plt.close()

# ------------------------------------------------------------
# 7. AVERAGE DELAY BY PROJECT TYPE
# ------------------------------------------------------------

if "project_type" in df.columns:
    delay_by_type = (
        df.groupby("project_type")["total_delay_days"]
        .mean()
        .sort_values(ascending=False)
        .round(2)
    )

    delay_by_type.to_csv(
        output_dir / "average_delay_by_project_type.csv"
    )

    plt.figure(figsize=(10, 5))
    delay_by_type.plot(kind="bar")
    plt.title("Average Total Delay by Project Type")
    plt.xlabel("Project Type")
    plt.ylabel("Average Delay (Days)")
    plt.xticks(rotation=35, ha="right")
    plt.tight_layout()
    plt.savefig(
        output_dir / "average_delay_by_project_type.png",
        dpi=200,
    )
    plt.close()

# ------------------------------------------------------------
# 8. STATE-WISE RECORD COUNT
# ------------------------------------------------------------

if "state" in df.columns:
    state_counts = df["state"].value_counts().head(15)

    plt.figure(figsize=(10, 5))
    state_counts.plot(kind="bar")
    plt.title("Top States by Number of Records")
    plt.xlabel("State")
    plt.ylabel("Number of Records")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(output_dir / "state_wise_record_count.png", dpi=200)
    plt.close()

# ------------------------------------------------------------
# 9. STATE-WISE RISK ANALYSIS
# ------------------------------------------------------------

if "state" in df.columns and "risk_level" in df.columns:
    state_risk_analysis = (
        df.groupby("state")
        .agg(
            total_records=("risk_level", "size"),
            high_risk_records=("risk_level", lambda values: (values == "HIGH").sum()),
            average_delay_days=("total_delay_days", "mean"),
            average_acquisition_percent=("acquisition_percent", "mean"),
        )
        .reset_index()
    )

    state_risk_analysis["high_risk_percentage"] = (
        state_risk_analysis["high_risk_records"]
        / state_risk_analysis["total_records"]
        * 100
    ).round(2)

    state_risk_analysis["average_delay_days"] = (
        state_risk_analysis["average_delay_days"].round(2)
    )

    state_risk_analysis["average_acquisition_percent"] = (
        state_risk_analysis["average_acquisition_percent"].round(2)
    )

    state_risk_analysis = state_risk_analysis.sort_values(
        by="high_risk_percentage",
        ascending=False,
    )

    state_risk_analysis.to_csv(
        output_dir / "state_wise_risk_analysis.csv",
        index=False,
    )

    top_states = state_risk_analysis.head(15)

    plt.figure(figsize=(10, 5))
    plt.bar(
        top_states["state"],
        top_states["high_risk_percentage"],
    )
    plt.title("State-wise High-Risk Percentage")
    plt.xlabel("State")
    plt.ylabel("High-Risk Records (%)")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(
        output_dir / "state_wise_high_risk_percentage.png",
        dpi=200,
    )
    plt.close()

# ------------------------------------------------------------
# 10. HIGH-PRIORITY RECORDS EXPORT
# ------------------------------------------------------------


high_priority = df[
    (df["total_delay_days"] > 30)
    & (df["acquisition_percent"] < 70)
].sort_values(
    by="total_delay_days",
    ascending=False,
)

high_priority.to_csv(
    output_dir / "high_priority_records.csv",
    index=False,
)

print("\nAnalytics completed successfully!")
print("Data source:", csv_file)
print("Output folder:", output_dir)
print("Acquisition-delay correlation:", round(correlation, 4))
print("\nGenerated files:")

for file in sorted(output_dir.iterdir()):
    print("-", file.name)
